'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSESB
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSESB.ESBSoap")>  _
    Public Interface ESBSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion_pedido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoCliente", ReplyAction:="*")>  _
        Function PedidoCliente(ByVal request As WSESB.PedidoClienteRequest) As WSESB.PedidoClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoCliente", ReplyAction:="*")>  _
        Function PedidoClienteAsync(ByVal request As WSESB.PedidoClienteRequest) As System.Threading.Tasks.Task(Of WSESB.PedidoClienteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EstadoPedidoRestauranteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoRestaurante", ReplyAction:="*")>  _
        Function EstadoPedidoRestaurante(ByVal request As WSESB.EstadoPedidoRestauranteRequest) As WSESB.EstadoPedidoRestauranteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoRestaurante", ReplyAction:="*")>  _
        Function EstadoPedidoRestauranteAsync(ByVal request As WSESB.EstadoPedidoRestauranteRequest) As System.Threading.Tasks.Task(Of WSESB.EstadoPedidoRestauranteResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EstadoPedidoRepartidorResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoRepartidor", ReplyAction:="*")>  _
        Function EstadoPedidoRepartidor(ByVal request As WSESB.EstadoPedidoRepartidorRequest) As WSESB.EstadoPedidoRepartidorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstadoPedidoRepartidor", ReplyAction:="*")>  _
        Function EstadoPedidoRepartidorAsync(ByVal request As WSESB.EstadoPedidoRepartidorRequest) As System.Threading.Tasks.Task(Of WSESB.EstadoPedidoRepartidorResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_repartidor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoListoRepartidor", ReplyAction:="*")>  _
        Function PedidoListoRepartidor(ByVal request As WSESB.PedidoListoRepartidorRequest) As WSESB.PedidoListoRepartidorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoListoRepartidor", ReplyAction:="*")>  _
        Function PedidoListoRepartidorAsync(ByVal request As WSESB.PedidoListoRepartidorRequest) As System.Threading.Tasks.Task(Of WSESB.PedidoListoRepartidorResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PedidoEntregadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoEntregado", ReplyAction:="*")>  _
        Function PedidoEntregado(ByVal request As WSESB.PedidoEntregadoRequest) As WSESB.PedidoEntregadoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PedidoEntregado", ReplyAction:="*")>  _
        Function PedidoEntregadoAsync(ByVal request As WSESB.PedidoEntregadoRequest) As System.Threading.Tasks.Task(Of WSESB.PedidoEntregadoResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoClienteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoCliente", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.PedidoClienteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.PedidoClienteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoClienteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public descripcion_pedido As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal descripcion_pedido As String)
            MyBase.New
            Me.descripcion_pedido = descripcion_pedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoClienteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoClienteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.PedidoClienteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.PedidoClienteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoClienteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PedidoClienteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PedidoClienteResult As String)
            MyBase.New
            Me.PedidoClienteResult = PedidoClienteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoRestauranteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoRestaurante", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.EstadoPedidoRestauranteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.EstadoPedidoRestauranteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoRestauranteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer)
            MyBase.New
            Me.idpedido = idpedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoRestauranteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoRestauranteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.EstadoPedidoRestauranteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.EstadoPedidoRestauranteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoRestauranteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EstadoPedidoRestauranteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EstadoPedidoRestauranteResult As String)
            MyBase.New
            Me.EstadoPedidoRestauranteResult = EstadoPedidoRestauranteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoRepartidorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoRepartidor", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.EstadoPedidoRepartidorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.EstadoPedidoRepartidorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoRepartidorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer)
            MyBase.New
            Me.idpedido = idpedido
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EstadoPedidoRepartidorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EstadoPedidoRepartidorResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.EstadoPedidoRepartidorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.EstadoPedidoRepartidorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoPedidoRepartidorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EstadoPedidoRepartidorResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EstadoPedidoRepartidorResult As String)
            MyBase.New
            Me.EstadoPedidoRepartidorResult = EstadoPedidoRepartidorResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoListoRepartidorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoListoRepartidor", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.PedidoListoRepartidorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.PedidoListoRepartidorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoListoRepartidorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public nombre_repartidor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer, ByVal nombre_repartidor As String)
            MyBase.New
            Me.idpedido = idpedido
            Me.nombre_repartidor = nombre_repartidor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoListoRepartidorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoListoRepartidorResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.PedidoListoRepartidorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.PedidoListoRepartidorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoListoRepartidorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PedidoListoRepartidorResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PedidoListoRepartidorResult As String)
            MyBase.New
            Me.PedidoListoRepartidorResult = PedidoListoRepartidorResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoEntregadoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoEntregado", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.PedidoEntregadoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.PedidoEntregadoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoEntregadoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public idpedido As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public nombre_repartidor As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idpedido As Integer, ByVal nombre_repartidor As Integer)
            MyBase.New
            Me.idpedido = idpedido
            Me.nombre_repartidor = nombre_repartidor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidoEntregadoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidoEntregadoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSESB.PedidoEntregadoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSESB.PedidoEntregadoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PedidoEntregadoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PedidoEntregadoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PedidoEntregadoResult As String)
            MyBase.New
            Me.PedidoEntregadoResult = PedidoEntregadoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ESBSoapChannel
        Inherits WSESB.ESBSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ESBSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSESB.ESBSoap)
        Implements WSESB.ESBSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_PedidoCliente(ByVal request As WSESB.PedidoClienteRequest) As WSESB.PedidoClienteResponse Implements WSESB.ESBSoap.PedidoCliente
            Return MyBase.Channel.PedidoCliente(request)
        End Function
        
        Public Function PedidoCliente(ByVal descripcion_pedido As String) As String
            Dim inValue As WSESB.PedidoClienteRequest = New WSESB.PedidoClienteRequest()
            inValue.Body = New WSESB.PedidoClienteRequestBody()
            inValue.Body.descripcion_pedido = descripcion_pedido
            Dim retVal As WSESB.PedidoClienteResponse = CType(Me,WSESB.ESBSoap).PedidoCliente(inValue)
            Return retVal.Body.PedidoClienteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_PedidoClienteAsync(ByVal request As WSESB.PedidoClienteRequest) As System.Threading.Tasks.Task(Of WSESB.PedidoClienteResponse) Implements WSESB.ESBSoap.PedidoClienteAsync
            Return MyBase.Channel.PedidoClienteAsync(request)
        End Function
        
        Public Function PedidoClienteAsync(ByVal descripcion_pedido As String) As System.Threading.Tasks.Task(Of WSESB.PedidoClienteResponse)
            Dim inValue As WSESB.PedidoClienteRequest = New WSESB.PedidoClienteRequest()
            inValue.Body = New WSESB.PedidoClienteRequestBody()
            inValue.Body.descripcion_pedido = descripcion_pedido
            Return CType(Me,WSESB.ESBSoap).PedidoClienteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_EstadoPedidoRestaurante(ByVal request As WSESB.EstadoPedidoRestauranteRequest) As WSESB.EstadoPedidoRestauranteResponse Implements WSESB.ESBSoap.EstadoPedidoRestaurante
            Return MyBase.Channel.EstadoPedidoRestaurante(request)
        End Function
        
        Public Function EstadoPedidoRestaurante(ByVal idpedido As Integer) As String
            Dim inValue As WSESB.EstadoPedidoRestauranteRequest = New WSESB.EstadoPedidoRestauranteRequest()
            inValue.Body = New WSESB.EstadoPedidoRestauranteRequestBody()
            inValue.Body.idpedido = idpedido
            Dim retVal As WSESB.EstadoPedidoRestauranteResponse = CType(Me,WSESB.ESBSoap).EstadoPedidoRestaurante(inValue)
            Return retVal.Body.EstadoPedidoRestauranteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_EstadoPedidoRestauranteAsync(ByVal request As WSESB.EstadoPedidoRestauranteRequest) As System.Threading.Tasks.Task(Of WSESB.EstadoPedidoRestauranteResponse) Implements WSESB.ESBSoap.EstadoPedidoRestauranteAsync
            Return MyBase.Channel.EstadoPedidoRestauranteAsync(request)
        End Function
        
        Public Function EstadoPedidoRestauranteAsync(ByVal idpedido As Integer) As System.Threading.Tasks.Task(Of WSESB.EstadoPedidoRestauranteResponse)
            Dim inValue As WSESB.EstadoPedidoRestauranteRequest = New WSESB.EstadoPedidoRestauranteRequest()
            inValue.Body = New WSESB.EstadoPedidoRestauranteRequestBody()
            inValue.Body.idpedido = idpedido
            Return CType(Me,WSESB.ESBSoap).EstadoPedidoRestauranteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_EstadoPedidoRepartidor(ByVal request As WSESB.EstadoPedidoRepartidorRequest) As WSESB.EstadoPedidoRepartidorResponse Implements WSESB.ESBSoap.EstadoPedidoRepartidor
            Return MyBase.Channel.EstadoPedidoRepartidor(request)
        End Function
        
        Public Function EstadoPedidoRepartidor(ByVal idpedido As Integer) As String
            Dim inValue As WSESB.EstadoPedidoRepartidorRequest = New WSESB.EstadoPedidoRepartidorRequest()
            inValue.Body = New WSESB.EstadoPedidoRepartidorRequestBody()
            inValue.Body.idpedido = idpedido
            Dim retVal As WSESB.EstadoPedidoRepartidorResponse = CType(Me,WSESB.ESBSoap).EstadoPedidoRepartidor(inValue)
            Return retVal.Body.EstadoPedidoRepartidorResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_EstadoPedidoRepartidorAsync(ByVal request As WSESB.EstadoPedidoRepartidorRequest) As System.Threading.Tasks.Task(Of WSESB.EstadoPedidoRepartidorResponse) Implements WSESB.ESBSoap.EstadoPedidoRepartidorAsync
            Return MyBase.Channel.EstadoPedidoRepartidorAsync(request)
        End Function
        
        Public Function EstadoPedidoRepartidorAsync(ByVal idpedido As Integer) As System.Threading.Tasks.Task(Of WSESB.EstadoPedidoRepartidorResponse)
            Dim inValue As WSESB.EstadoPedidoRepartidorRequest = New WSESB.EstadoPedidoRepartidorRequest()
            inValue.Body = New WSESB.EstadoPedidoRepartidorRequestBody()
            inValue.Body.idpedido = idpedido
            Return CType(Me,WSESB.ESBSoap).EstadoPedidoRepartidorAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_PedidoListoRepartidor(ByVal request As WSESB.PedidoListoRepartidorRequest) As WSESB.PedidoListoRepartidorResponse Implements WSESB.ESBSoap.PedidoListoRepartidor
            Return MyBase.Channel.PedidoListoRepartidor(request)
        End Function
        
        Public Function PedidoListoRepartidor(ByVal idpedido As Integer, ByVal nombre_repartidor As String) As String
            Dim inValue As WSESB.PedidoListoRepartidorRequest = New WSESB.PedidoListoRepartidorRequest()
            inValue.Body = New WSESB.PedidoListoRepartidorRequestBody()
            inValue.Body.idpedido = idpedido
            inValue.Body.nombre_repartidor = nombre_repartidor
            Dim retVal As WSESB.PedidoListoRepartidorResponse = CType(Me,WSESB.ESBSoap).PedidoListoRepartidor(inValue)
            Return retVal.Body.PedidoListoRepartidorResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_PedidoListoRepartidorAsync(ByVal request As WSESB.PedidoListoRepartidorRequest) As System.Threading.Tasks.Task(Of WSESB.PedidoListoRepartidorResponse) Implements WSESB.ESBSoap.PedidoListoRepartidorAsync
            Return MyBase.Channel.PedidoListoRepartidorAsync(request)
        End Function
        
        Public Function PedidoListoRepartidorAsync(ByVal idpedido As Integer, ByVal nombre_repartidor As String) As System.Threading.Tasks.Task(Of WSESB.PedidoListoRepartidorResponse)
            Dim inValue As WSESB.PedidoListoRepartidorRequest = New WSESB.PedidoListoRepartidorRequest()
            inValue.Body = New WSESB.PedidoListoRepartidorRequestBody()
            inValue.Body.idpedido = idpedido
            inValue.Body.nombre_repartidor = nombre_repartidor
            Return CType(Me,WSESB.ESBSoap).PedidoListoRepartidorAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_PedidoEntregado(ByVal request As WSESB.PedidoEntregadoRequest) As WSESB.PedidoEntregadoResponse Implements WSESB.ESBSoap.PedidoEntregado
            Return MyBase.Channel.PedidoEntregado(request)
        End Function
        
        Public Function PedidoEntregado(ByVal idpedido As Integer, ByVal nombre_repartidor As Integer) As String
            Dim inValue As WSESB.PedidoEntregadoRequest = New WSESB.PedidoEntregadoRequest()
            inValue.Body = New WSESB.PedidoEntregadoRequestBody()
            inValue.Body.idpedido = idpedido
            inValue.Body.nombre_repartidor = nombre_repartidor
            Dim retVal As WSESB.PedidoEntregadoResponse = CType(Me,WSESB.ESBSoap).PedidoEntregado(inValue)
            Return retVal.Body.PedidoEntregadoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSESB_ESBSoap_PedidoEntregadoAsync(ByVal request As WSESB.PedidoEntregadoRequest) As System.Threading.Tasks.Task(Of WSESB.PedidoEntregadoResponse) Implements WSESB.ESBSoap.PedidoEntregadoAsync
            Return MyBase.Channel.PedidoEntregadoAsync(request)
        End Function
        
        Public Function PedidoEntregadoAsync(ByVal idpedido As Integer, ByVal nombre_repartidor As Integer) As System.Threading.Tasks.Task(Of WSESB.PedidoEntregadoResponse)
            Dim inValue As WSESB.PedidoEntregadoRequest = New WSESB.PedidoEntregadoRequest()
            inValue.Body = New WSESB.PedidoEntregadoRequestBody()
            inValue.Body.idpedido = idpedido
            inValue.Body.nombre_repartidor = nombre_repartidor
            Return CType(Me,WSESB.ESBSoap).PedidoEntregadoAsync(inValue)
        End Function
    End Class
End Namespace
